### ISSUE TITLE
Collect official text for the ballot measures

### ISSUE THREAD

**Issue by elinaru** [caciviclab/disclosure-frontend-alpha#4]
1. Determine the 2014 and 2015 SF ballot measures.
2. Gather text from Ballotpedia (http://ballotpedia.org/San_Francisco_City_and_County,_California_ballot_measures)
3. Enter data in [TBA location that feeds into interface]

**Comment by bayreporta** [comment]
How much text do we need? Do we need just official summaries or also the pros/cons?

**Comment by bayreporta** [comment]
Proposition A

To finance the construction, development, acquisition, and preservation of housing affordable to low- and middle-income households through programs that will prioritize vulnerable populations such as San Francisco’s working families, veterans, seniors, disabled persons; to assist in the acquisition, rehabilitation, and preservation of affordable rental apartment buildings to prevent the eviction of long-term residents; to repair and reconstruct dilapidated public housing; to fund a middle-income rental program; and to provide for homeownership down payment assistance opportunities for educators and middle-income households; shall the City and County of San Francisco issue $310 million in general obligation bonds, subject to independent citizen oversight and regular audits?

**Comment by bayreporta** [comment]
Prop B

Shall the City amend the Charter to allow parents who are both City employees to each take the maximum amount of paid parental leave for which they qualify for the birth, adoption or foster parenting of the same child, if both parents are City employees; and to provide each parent the opportunity to keep up to 40 hours of sick leave at the end of paid parental leave?

**Comment by bayreporta** [comment]
Prop C

Shall the City regulate expenditure lobbyists by requiring them to register with the Ethics Commission, pay a $500 registration fee, and file monthly disclosures regarding their lobbying activities?

**Comment by bayreporta** [comment]
Prop D

Shall the City increase the height limit for 10 of the 28 acres of the Mission Rock site from one story to height limits ranging from 40 to 240 feet and make it City policy to encourage the development on the Mission Rock site provided that it includes eight acres of parks and open space and housing of which at least 33% is affordable for low- and middle-income households?

**Comment by bayreporta** [comment]
Prop E

Shall the City broadcast all City meetings live on the Internet; allow members of the public to submit electronically during the meeting live, written, video, or audio comments from any location and require those comments be played; require pre-recorded video testimony to be played during a meeting; and allow the public or board, commission, or committee members to request that discussion of a particular agenda item begin at a specific time?

**Comment by bayreporta** [comment]
Prop F

Shall the City limit short-term rentals of a housing unit to 75 days per year regardless of whether the rental is hosted or unhosted; require owners to provide proof that they authorize the unit as a short-term rental; require residents who offer short-term rentals to submit quarterly reports on the number of days they live in the unit and the number of days the unit is rented; prohibit short-term rentals of in-law units; allow interested parties to sue hosting platforms; and make it a misdemeanor for a hosting platform to unlawfully list a unit as a short-term rental?

**Comment by bayreporta** [comment]
Prop G

Shall the City define ‘renewable, greenhouse-gas free electricity’ to mean electricity derived exclusively from certain renewable resources located within or adjacent to the California border or electricity derived from Hetch Hetchy, except for electricity from other types of resources such as rooftop solar and other large hydroelectric facilities; require CleanPowerSF to inform customers and potential customers of the planned percentage of ‘renewable, greenhouse-gas free electricity’ to be provided; and prohibit CleanPowerSF from marketing, advertising or making any public statement that its electricity is ‘clean’ or ‘green’ unless the electricity is ‘renewable, greenhouse gas-free electricity’ as defined in this measure?

**Comment by bayreporta** [comment]
Prop H

Shall the City use the State definition of ‘eligible renewable energy resources’ when referring to terms such as ‘clean energy,’ ‘green energy,’ and ‘renewable Greenhouse Gas-free Energy’; and shall CleanPowerSF be urged to inform customers and potential customers of the planned percentage of types of renewable energy to be supplied in each communication; and shall it be City policy for CleanPowerSF to use electricity generated within California and San Francisco when possible?

**Comment by bayreporta** [comment]
Prop I

Shall the City suspend the issuance of permits on certain types of housing and business development projects in the Mission District for at least 18 months; and develop a Neighborhood Stabilization Plan for the Mission District by January 31, 2017?

**Comment by bayreporta** [comment]
Prop J

Shall the City establish a Legacy Business Historic Preservation Fund, which would give grants to Legacy Businesses and to building owners who lease space to those businesses for terms of at least 10 years; and expand the definition of a Legacy Business to include those that have operated in San Francisco for more than 20 years, are at risk of displacement and meet the other requirements of the Registry?

**Comment by bayreporta** [comment]
Prop K

Shall the City to expand the allowable uses of surplus property to include building affordable housing for a range of households from those who are homeless or those with very low income to those with incomes up to 120% of the area median income; and, for projects of more than 200 units, make some housing available for households earning up to 150% or more of the area median income?

**Comment by bayreporta** [comment]
Without knowing how much detail is going into these pages, I just grabbed the ballot questions: most straightforward description of the measure.

**Comment by elinaru** [comment]
Maybe the ballot questions are enough. Thanks John --

**Comment by evanwolf** [comment]
The pros and cons are interesting because of who writes them, signs them. A clue about the moneyed interests at work, and whether they have power or not.

**Comment by adborden** [comment]
FYI adding django models so that you'll be able to enter these right from disclosure.caciviclab.org.. I'll keep you posted.

**Comment by adborden** [comment]
You can add ballot information here http://disclosure.caciviclab.org/admin/ballot/ ping in slack for access.

**Comment by bayreporta** [comment]
So what's the conclusion? Are we adding more than the ballot question? Also, can I insert html into Django backend?

**Comment by bayreporta** [comment]
I've added all the ballot measures with questions.

**Comment by bayreporta** [comment]
All the summary and pro/con text for the ballots I'm getting from http://voterguide.sfelections.org/

**Comment by bayreporta** [comment]
Done.
