### ISSUE TITLE
Standardize API on locality_id

### ISSUE THREAD

**Issue by bcipolli** [caciviclab/disclosure-frontend-alpha#52]
I've seen in a few code snippets uses of [`fips_id`](https://github.com/caciviclab/disclosure-frontend-alpha/blob/483050ed9eeff97fd72ab39076ebf880ee3ee010/app/appRoutes.js#L41) and [`fip_id`](https://github.com/caciviclab/disclosure-frontend-alpha/blob/483050ed9eeff97fd72ab39076ebf880ee3ee010/app/components/homePageModule/homePage.html#L26)

Seems to me we should be using `fips_id` ([Federal Information Processing Standard](https://www.google.com/search?q=fips+code)) on the front-end and back-end. Just wanted to check with others if there's any reason to use `fip_id`, or to alternate between the two?

**Comment by tdooner** [comment]
No reason to use `fip_id`, we should standardize on `fips_id`.

**Comment by bcipolli** [comment]
Just saw this while running the front-end server: gulp-jscs is complaining about `fips_id`:

![image](https://cloud.githubusercontent.com/assets/4072455/11943199/c4c7d8ca-a7f0-11e5-8407-69eccb9f5b32.png)

**Comment by jnmarcus** [comment]
I agree with @tdooner on standardizing to fips_id.  @bcipolli gulp-jscs doesn't like a lot of things currently we should probably adjust it based on what the team decides.  What does the backend/API team prefer? We can adjust .jscs file accordingly, unless you guys think UPPER_CASE is better, and want to change the values coming back to reflect that...

**Comment by bcipolli** [comment]
Final conclusion is that `fips_id` is *not* the right abstraction. Instead, we should use a `locality_id`. Updated the title.

**Comment by bcipolli** [comment]
Fixed by #77
