### ISSUE TITLE
Prepare candidate bios, campaign websites, and twitter accounts

### ISSUE THREAD

**Issue by elinaru** [caciviclab/disclosure-frontend-alpha#6]
From League of Women Voters' site?

**Comment by bayreporta** [comment]
I'd recommend Ballotpedia. Much more detail there than Smart Voter

**Comment by adborden** [comment]
You can upload this information here http://disclosure.caciviclab.org/admin/ballot/candidate/ ping me for access.

**Comment by bayreporta** [comment]
@adborden ping

**Comment by bayreporta** [comment]
So actually there isn't a good solid place to get consistent bios. Suggestions?

**Comment by bayreporta** [comment]
So sfelections does have an area where candidates can submit statements. That might be the fairest place to go as all the candidates have submitted. @adborden that would require us changing "bio" to "statements" if we go that route.

**Comment by adborden** [comment]
Removing v1, as discussed https://docs.google.com/document/d/1cLhf4AICeDVf1yxLjt1e1DtrjxvZGEmerBHOTwm6QoY/edit#

Ballot measures seem to be simpler to implement and make more sense as a first goal. Candidates will follow soon after.

**Comment by adborden** [comment]
Ah, scratch that, I think we were only talking about candidate campaign finance data. I'll circle back to confirm.

**Comment by amandaric** [comment]
@adborden Can you give me access to Django so that I can see where to upload content? Thanks!

**Comment by adborden** [comment]
On Tue, 2015-10-20 at 20:34 -0700, amandaric <notifications@github.com> wrote:
> @adborden Can you give me access to Django so that I can see where to upload content? Thanks!

Done :) pinged you the password on slack.


--
Aaron Borden
Human and Hacker

**Comment by amandaric** [comment]
@aborden Can we create a 'sources' section for each candidate bio on django?

**Comment by amandaric** [comment]
San Francisco candidate bios are complete. Here is Google excel doc containing the same data: https://docs.google.com/spreadsheets/d/1S92cpxwIqltR8sNBoL8BSjhCk8kQy-603uwuOt3JRT0/edit?usp=sharing
